module.exports = {
  siteTitle: 'Gatsby Demo',
  siteDescription: 'Simple gatsby example for tutorial',
  siteUrl: 'http://localhost:8000',
  publicPath: 'http://localhost:8000/',
  apiUrl: 'http://localhost:1337',
  manifestName: 'Gatsby Demo - Simple gatsby example',
  manifestShortName: 'GatsbyDemo',
  manifestStartUrl: '/',
  manifestBackgroundColor: '#ffffff',
  manifestThemeColor: '#ffffff',
  manifestDisplay: 'standalone',
  authorName: 'My Name',
  authorProfile: 'My Profile',
  authorSocialLinks: {
    twitter: 'https://twitter.com/',
    github: 'https://github.com/',
    qiita: 'https://qiita.com/',
  },
  gaTrackingID: 'UA-XXXXXXXXX-X',
}
